### ISSUE TITLE
Test flakes

### ISSUE THREAD

**Issue by jonmmease** [vega/vl-convert#101]
vl-convert-rs-tests flaked on Linux once with:

```
failures:

---- test_png_no_theme::test::case_10 stdout ----
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(109), ...)', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.204.0/runtime/jsruntime.rs:1930:46
thread 'test_png_no_theme::test::case_10' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to retrieve conversion result: oneshot canceled', vl-convert-rs/tests/test_specs.rs:353:11
```

Passed on restart. Something to keep an eye on.

**Comment by jonmmease** [comment]
Another one
```
---- test_png_no_theme::test::case_10 stdout ----
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_ffi-0.105.0/lib.rs:128:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_png_no_theme::test::case_10' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to retrieve conversion result: oneshot canceled', vl-convert-rs/tests/test_specs.rs:353:11
```

**Comment by jonmmease** [comment]
Cross reference discussion in https://github.com/denoland/deno/issues/19670 where it was advised that the current-thread tokio runtime should be used with Deno. This may mean that the Rust tests should not be run concurrently: https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively.

**Comment by jonmmease** [comment]
Haven't seen these in a while, going to close for now
