### ISSUE TITLE
deno_fetch BorrowMutError with 0.11.1

### ISSUE THREAD

**Issue by jonmmease** [vega/vl-convert#78]
After updating from 0.10.3 to 0.11.1, the Altair CI tests are failing flakily with this error:

```
thread 'tokio-runtime-worker' panicked at 'already borrowed: BorrowMutError', /Users/jonmmease/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_fetch-0.132.0/lib.rs:453:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(262), ...)', /Users/jonmmease/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.190.0/runtime.rs:2432:50

stack backtrace:
   0:        0x178465454 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   1:        0x178071b18 - _BrotliDecoderVersion
   2:        0x1784438c4 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   3:        0x178469384 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   4:        0x178468fe4 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   5:        0x178469ed0 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   6:        0x178469a80 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   7:        0x1784699f0 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   8:        0x1784699e4 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   9:        0x17958ca1c - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  10:        0x17958cc68 - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  11:        0x17810410c - _BrotliDecoderVersion
  12:        0x1781068d0 - _BrotliDecoderVersion
  13:        0x17809f8f8 - _BrotliDecoderVersion
  14:        0x1780b6a70 - _BrotliDecoderVersion
  15:        0x178493b54 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  16:        0x178492aa8 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  17:        0x1784a05a0 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  18:        0x17849801c - _rustsecp256k1_v0_8_1_default_error_callback_fn
  19:        0x178497bf0 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  20:        0x178498580 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  21:        0x17846bc80 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  22:        0x19c227fa8 - __pthread_joiner_wake
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(137), ...)', /Users/jonmmease/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.190.0/runtime.rs:2432:50
stack backtrace:
   0:        0x178465454 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   1:        0x178071b18 - _BrotliDecoderVersion
   2:        0x1784438c4 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   3:        0x178469384 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   4:        0x178468fe4 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   5:        0x178469ed0 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   6:        0x178469a80 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   7:        0x1784699f0 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   8:        0x1784699e4 - _rustsecp256k1_v0_8_1_default_error_callback_fn
   9:        0x17958ca1c - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  10:        0x17958cc68 - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  11:        0x1780a923c - _BrotliDecoderVersion
  12:        0x17851b9cc - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  13:        0x17851d06c - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  14:        0x178516f50 - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  15:        0x178529b08 - _v8_inspector__V8InspectorClient__BASE__consoleAPIMessage
  16:        0x17846bc80 - _rustsecp256k1_v0_8_1_default_error_callback_fn
  17:        0x19c227fa8 - __pthread_joiner_wake
```

This is the error both locally on an M1 mac and on CI on linux-64

**Comment by jonmmease** [comment]
Reported in https://github.com/denoland/deno/issues/19670
